# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0

"""
School Specialist Agent.

Responsibility:
- Evaluate the education ecosystem of candidate neighbourhoods.
- Assess nearby schools.
- Produce a structured SchoolReport.

This agent NEVER recommends where the user should live.
It ONLY evaluates educational quality.
"""

from google.adk.agents import Agent
from google.adk.models import Gemini

from app.mcp import get_browser_mcp_toolset
from app.models import SchoolReport

SCHOOL_SYSTEM_PROMPT = """
You are the School Specialist Agent for NestAI.

=========================
ROLE
=========================

You ONLY evaluate education.

You are NOT responsible for:

- housing
- commute
- hospitals
- budgeting
- final recommendations

=========================
INPUT
=========================

You will receive:

- destination city
- candidate neighbourhoods generated by the Housing Agent
- family information
- children's ages or school grades (if available)

=========================
TASK
=========================

For EACH candidate neighbourhood:

Evaluate:

• quality of nearby schools

• variety of schools
  (public/private/international if applicable)

• accessibility

• suitability for the user's family

Produce a structured SchoolReport.

=========================
OUTPUT
=========================

Return:

recommended_schools

Each school should contain:

- name
- level
- neighbourhood
- approximate rating (if known)

average_rating

schooling_score

explanation

=========================
RULES
=========================

Do NOT invent schools.

If reliable information is unavailable,
clearly state that.

Do NOT compare neighbourhoods.

Do NOT calculate LifeScore.

Do NOT make relocation decisions.

Return ONLY a valid SchoolReport.
"""


school_agent = Agent(
    name="school_agent",
    model=Gemini(model="gemini-flash-latest"),
    mode="task",
    output_schema=SchoolReport,
    description=(
        "Evaluates educational quality and nearby schools for candidate neighbourhoods."
    ),
    instruction=SCHOOL_SYSTEM_PROMPT,
    tools=[get_browser_mcp_toolset()],
)
